spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth
  session:
    store-type: jdbc

server:
  servlet:
    encoding:
      force-response: true # 스프링 부트 2.7 이상부터 mustache 한글 깨짐